name: Salesforce Deployment

on:
  push:
    branches:
      - Dev1
      - SIT
      - UAT
      - master  # Ensure this matches your main branch name

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install msys2
      run: |
        choco install -y msys2
        refreshenv
        C:\msys64\usr\bin\bash -lc "pacman -Syuu --noconfirm"
        C:\msys64\usr\bin\bash -lc "pacman -S --noconfirm base-devel gcc vim"
        echo "msys2 installed successfully"

    - name: Verify ant-salesforce.jar
      shell: bash
      run: |
        if [ ! -f ./lib/ant-salesforce.jar ]; then
          echo "ant-salesforce.jar not found in lib directory"
          exit 1
        fi

    - name: Set Environment Variables
      shell: bash
      run: |
        echo "Setting environment variables..."
        case ${{ github.ref_name }} in
          Dev1|SIT|UAT)
            echo "SF_USERNAME=${{ secrets.SF_USERNAME_SANDBOX }}" >> $GITHUB_ENV
            echo "SF_PASSWORD=${{ secrets.SF_PASSWORD_SANDBOX }}" >> $GITHUB_ENV
            echo "SF_SERVERURL=${{ secrets.SF_SERVERURL_SANDBOX }}" >> $GITHUB_ENV
            ;;
          master)
            echo "SF_USERNAME=${{ secrets.SF_USERNAME_PROD }}" >> $GITHUB_ENV
            echo "SF_PASSWORD=${{ secrets.SF_PASSWORD_PROD }}" >> $GITHUB_ENV
            echo "SF_SERVERURL=${{ secrets.SF_SERVERURL_PROD }}" >> $GITHUB_ENV
            ;;
        esac

    - name: Set Org Alias
      shell: bash
      run: |
        case ${{ github.ref_name }} in
          Dev1)
            echo "ORG_ALIAS=Dev1" >> $GITHUB_ENV
            ;;
          SIT)
            echo "ORG_ALIAS=SIT" >> $GITHUB_ENV
            ;;
          UAT)
            echo "ORG_ALIAS=UAT" >> $GITHUB_ENV
            ;;
          master)
            echo "ORG_ALIAS=prod" >> $GITHUB_ENV
            ;;
        esac

    - name: Run Salesforce CLI Installation
      shell: bash
      run: ./install_sfdx.bat

    - name: Run Ant Deployment
      shell: bash
      run: |
        ant -lib ./lib -f build.xml deploy -Dsf.username=${{ env.SF_USERNAME }} -Dsf.password=${{ env.SF_PASSWORD }} -Dsf.serverurl=${{ env.SF_SERVERURL }} -Dorg.alias=${{ env.ORG_ALIAS }}
