name: Salesforce Deployment

on:
  push:
    branches:
      - Dev1
      - SIT
      - UAT
      - master  # Ensure this matches your main branch name

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Salesforce CLI
      run: npm install --global sfdx-cli

    - name: Add Salesforce CLI to Path
      run: echo "C:\Users\runneradmin\AppData\Roaming\npm" | Out-File -FilePath $env:GITHUB_PATH -Append

    - name: Verify ant-salesforce.jar
      run: |
        if [ ! -f ./lib/ant-salesforce.jar ]; then
          echo "ant-salesforce.jar not found in lib directory"
          exit 1
        fi

    - name: Set Environment Variables
      run: |
        echo "Setting environment variables..."
        if [ "${{ github.ref_name }}" == "Dev1" ] || [ "${{ github.ref_name }}" == "SIT" ] || [ "${{ github.ref_name }}" == "UAT" ]; then
          echo "SF_USERNAME=${{ secrets.SF_USERNAME_SANDBOX }}" >> $GITHUB_ENV
          echo "SF_PASSWORD=${{ secrets.SF_PASSWORD_SANDBOX }}" >> $GITHUB_ENV
          echo "SF_SERVERURL=${{ secrets.SF_SERVERURL_SANDBOX }}" >> $GITHUB_ENV
        elif [ "${{ github.ref_name }}" == "master" ]; then
          echo "SF_USERNAME=${{ secrets.SF_USERNAME_PROD }}" >> $GITHUB_ENV
          echo "SF_PASSWORD=${{ secrets.SF_PASSWORD_PROD }}" >> $GITHUB_ENV
          echo "SF_SERVERURL=${{ secrets.SF_SERVERURL_PROD }}" >> $GITHUB_ENV
        fi

    - name: Set Org Alias
      run: |
        if [ "${{ github.ref_name }}" == "Dev1" ]; then
          echo "ORG_ALIAS=Dev1" >> $GITHUB_ENV
        elif [ "${{ github.ref_name }}" == "SIT" ]; then
          echo "ORG_ALIAS=SIT" >> $GITHUB_ENV
        elif [ "${{ github.ref_name }}" == "UAT" ]; then
          echo "ORG_ALIAS=UAT" >> $GITHUB_ENV
        elif [ "${{ github.ref_name }}" == "master" ]; then
          echo "ORG_ALIAS=prod" >> $GITHUB_ENV
        fi

    - name: Run Ant Deployment
      run: |
        ant -lib ./lib -f build.xml deploy -Dsf.username=${{ env.SF_USERNAME }} -Dsf.password=${{ env.SF_PASSWORD }} -Dsf.serverurl=${{ env.SF_SERVERURL }} -Dorg.alias=${{ env.ORG_ALIAS }}
