name: Salesforce Deployment

on:
  push:
    branches:
      - Dev1
      - SIT
      - UAT
      - PROD

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Setup Ant
      run: |
        sudo apt-get update
        sudo apt-get install ant -y

    - name: Download Salesforce Ant Migration Tool
      run: |
        wget -q https://gs0.salesforce.com/dwnld/SfdcAnt/salesforce_ant_49.0.zip -O /tmp/salesforce_ant.zip
        unzip -qq /tmp/salesforce_ant.zip -d /tmp/
        mkdir -p ./lib
        cp /tmp/salesforce_ant_49.0/ant-salesforce.jar ./lib/

    - name: Deploy to Environment
      run: |
        case ${{ github.ref_name }} in
          Dev1|SIT|UAT)
            export ANT_ENV=sandbox
            ;;
          PROD)
            export ANT_ENV=prod
            ;;
        esac
        ant -lib ./lib -f build.xml deploy -Denv.${ANT_ENV}=${{ secrets.SF_ENV }}

    # - name: Notify ServiceNow of Deployment Success
    #   if: success()
    #   run: |
    #     curl -X POST "https://<your_instance>.service-now.com/api/now/table/incident" \
    #     --user "${{ secrets.SN_USERNAME }}:${{ secrets.SN_PASSWORD }}" \
    #     --header "Content-Type: application/json" \
    #     --data '{
    #       "short_description": "Deployment to ${{ github.ref_name }} Environment Successful",
    #       "description": "The deployment to the ${{ github.ref_name }} environment has been completed successfully.",
    #       "category": "Software",
    #       "subcategory": "Deployment",
    #       "u_environment": "${{ github.ref_name }}"
    #     }'
