name: Salesforce Deployment

on:
  push:
    branches:
      - Dev1
      - SIT
      - UAT
      - PROD

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Setup Ant
      run: |
        sudo apt-get update
        sudo apt-get install ant -y

    - name: Create lib directory
      run: mkdir -p ./lib

    - name: Download Salesforce Ant Migration Tool
      run: |
        wget -q https://gs0.salesforce.com/dwnld/SfdcAnt/salesforce_ant_59.0.zip -O ./lib/ant-salesforce.jar

    - name: Deploy to Environment
      env:
        SF_SERVERURL_PROD: ${{ secrets.SF_SERVERURL_PROD }}
        SF_SERVERURL_SANDBOX: ${{ secrets.SF_SERVERURL_SANDBOX }}
        SF_USERNAME: ${{ secrets.SF_USERNAME }}
        SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
        ENV: ${{ github.ref_name }}
      run: |
        case ${{ github.ref_name }} in
          Dev1|SIT|UAT)
            export ENV=sandbox
            ;;
          PROD)
            export ENV=prod
            ;;
        esac
        ant -lib ./lib -f build.xml deploy -Denv=${ENV}
