name: Salesforce Deployment

on:
  push:
    branches:
      - Dev1
      - SIT
      - UAT
      - PROD

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Setup Ant
      run: |
        sudo apt-get update
        sudo apt-get install ant -y

    - name: Verify lib directory
      run: ls -al ./lib

    - name: Deploy to Environment
      env:
        SF_SERVERURL_PROD: ${{ secrets.SF_SERVERURL_PROD }}
        SF_SERVERURL_SANDBOX: ${{ secrets.SF_SERVERURL_SANDBOX }}
        SF_USERNAME: ${{ secrets.SF_USERNAME }}
        SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
        ENV: ${{ github.ref_name }}
      run: |
        # Set environment based on branch
        case ${{ github.ref_name }} in
          Dev1|SIT|UAT)
            export ENV=sandbox
            export SF_SERVERURL=$SF_SERVERURL_SANDBOX
            ;;
          PROD)
            export ENV=prod
            export SF_SERVERURL=$SF_SERVERURL_PROD
            ;;
        esac

        # Print environment variables for debugging
        echo "Using environment: $ENV"
        echo "Salesforce server URL: $SF_SERVERURL"

        # Run the Ant build
        ant -lib ./lib -f build.xml deploy -Denv=${ENV}
