name: Salesforce Deployment

on:
  push:
    branches:
      - Dev1
      - SIT
      - UAT
      - PROD

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Setup Ant
      run: |
        choco install ant -y

    - name: Setup Salesforce DX CLI
      run: |
        Invoke-WebRequest -Uri https://developer.salesforce.com/media/salesforce-cli/sfdx-cli/channels/stable/sfdx-cli-windows-x64.exe -OutFile sfdx-cli.exe
        ./sfdx-cli.exe /quiet /norestart
        $env:Path += ";C:\Program Files\sfdx\bin"
        sfdx --version

    - name: Verify ant-salesforce.jar
      run: |
        if (!(Test-Path -Path ./lib/ant-salesforce.jar)) {
          Write-Error "ant-salesforce.jar not found in lib directory"
          exit 1
        }

    - name: Deploy to Environment
      env:
        SF_ENV: ${{ github.ref_name }}
      run: |
        case ${{ github.ref_name }} in
          Dev1|SIT|UAT)
            $env:SF_USERNAME=$(grep "sf.username.sandbox" build.properties | cut -d'=' -f2)
            $env:SF_PASSWORD=$(grep "sf.password.sandbox" build.properties | cut -d'=' -f2)
            $env:SF_SERVERURL=$(grep "sf.serverurl.sandbox" build.properties | cut -d'=' -f2)
            ;;
          PROD)
            $env:SF_USERNAME=$(grep "sf.username.prod" build.properties | cut -d'=' -f2)
            $env:SF_PASSWORD=$(grep "sf.password.prod" build.properties | cut -d'=' -f2)
            $env:SF_SERVERURL=$(grep "sf.serverurl.prod" build.properties | cut -d'=' -f2)
            ;;
        esac

        echo "Using environment: $env:SF_ENV"
        echo "Salesforce server URL: $env:SF_SERVERURL"

        ant -lib ./lib -f build.xml deploy -Dsf.username=$env:SF_USERNAME -Dsf.password=$env:SF_PASSWORD -Dsf.serverurl=$env:SF_SERVERURL
